### ISSUE TITLE
Controllers should not require directly the service locator

### ISSUE THREAD

**Issue by jbuget** [jbuget/nodejs-clean-architecture-app#14]
Service locator depends on environment and configuration modules/files. Thus its place is in `infrastructure` package.

For now, service locator is required directly by the controllers. This dependance breaks the golden rule that forbid an inner layered component to directly acccess outer layered component.

A solution may be to inject the service in every Hapi request. It then will be used by (for example, in a route handler/controller) `request.app.serviceLocator.userRepository`.

**Comment by Cleanshooter** [comment]
I think this is the reason I will never support Clean Architecture.  While your Controllers or Application layer may not explicitly depend on them through an import (or require) your still violating "Uncle Bob's Dependency Rule" because you still using it at the application level.  Unless I misread the rule.  For example your getUser function still relies on the ability to interact with a repository and with out it is useless which is why it calls return userRepository.get(userId);  

The getUser use cases is a redundant reference to the serviceLocator.get.  The service locator drives the entire application and just because its passed as an argument or hidden inside of the request object doesn't mean it's not a dependency. Just because its not using Dependency Injection doesn't mean that your controllers or application aren't dependent on them.  (https://en.wikipedia.org/wiki/Coupling_(computer_programming)). 

I'm trying to learn the details of Clean Architecture right now so please don't take this as me saying something is wrong.  I just don't understand how doing this help make better software.  By pass the service locator around and hiding it your doe is harder to read and follow (violating clean code principals) and forces us to add additional function argument which violates another clean code principal.  It's for these reasons that I really want to call BS on Uncle Bob's Dependency Rule... I think it make for bad code and bad architecture.
