### ISSUE TITLE
Why does an interface know about User entity?

### ISSUE THREAD

**Issue by imsergiobernal** [jbuget/nodejs-clean-architecture-app#3]
https://github.com/jbuget/nodejs-clean-architecture-app/blob/c759dafcb1f6d2c561488f1df04683c2979e37ed/lib/interfaces/storage/UserRepositoryInMemory.js#L4

I was looking here and I asked to myself, why does an interface know about the existance of User entity, if the next layer is Application?

**Comment by prashkup** [comment]
This issue is kinda old and you probably know the reason now.

The outer layers can know about the inner layers, not just the layers immediately below them. The inner layers cannot know anything about the outer layers, this is from uncle bob's post : 

"The overriding rule that makes this architecture work is The Dependency Rule. This rule says that source code dependencies can only point inwards. Nothing in an inner circle can know anything at all about something in an outer circle. In particular, the name of something declared in an outer circle must not be mentioned by the code in the an inner circle. That includes, functions, classes. variables, or any other named software entity"

**Comment by jbuget** [comment]
As I understand it, an external layer can know and access everything inside its own layer or a lower layer. Thus, a Repository implementation, situated in the interface layer, can know about the existence of a Use Case, a Repository definition or any Domain Entity.
